### ISSUE TITLE
Configure dependabot to work on monorepo

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#136]
Depends on: https://github.com/pol-is/polisServer/pull/60

Dependabot is already enabled on this repo. It runs weekly checks for individually updating deps one at a time. We need to tell it how to work on our monorepo.

https://dependabot.com/docs/config-file/

```yml
# .dependabot/config.yml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/clientAdmin"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/clientParticipation"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/fileServer"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/report"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/server"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/math"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/fileServer"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/clientAdmin"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/clientParticipation"
    update_schedule: "weekly"
```

Normally config is autodetected, but the above 3 keys are required for each when files aren't detected in the root.
